using System.Linq;
using System.Numerics;
using Content.Shared.Access;
using Content.Shared._Funkystation.Documents;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Funkystation.Documents.UI;

[GenerateTypedNameReferences]
public sealed partial class DocumentPrinterMenu : DefaultWindow
{
    [Dependency] private IPrototypeManager _proto = null!;
    [Dependency] private IEntityManager _entMan = null!;

    private readonly SpriteSystem _spriteSystem;
    public event Action<string>? OnPrintRequested;

    private DocumentPrinterBoundUserInterfaceState? _lastState;
    private string? _currentCategory;
    private bool _tabsBuilt;

    public DocumentPrinterMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entMan.System<SpriteSystem>();

        SearchBar.OnTextChanged += _ => RefreshDocumentList();
    }

    public void UpdateState(DocumentPrinterBoundUserInterfaceState state)
    {
        _lastState = state;

        // tabs are static
        if (!_tabsBuilt)
        {
            BuildTabs(state);
            _tabsBuilt = true;
        }

        RefreshDocumentList();
    }

    private void BuildTabs(DocumentPrinterBoundUserInterfaceState state)
    {
        CategoryList.RemoveAllChildren();

        var categories = state.DocumentsByCategory.Keys
            .Select(id => _proto.TryIndex<DocumentCategoryPrototype>(id, out var cat) ? cat : null)
            .OfType<DocumentCategoryPrototype>()
            .OrderBy(cat => cat.Priority)
            .ToList();

        foreach (var cat in categories)
        {
            var button = new Button
            {
                ToggleMode = true,
                HorizontalExpand = true,
                Name = $"CategoryTab_{cat.ID}"
            };

            var content = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
                HorizontalExpand = true
            };

            content.AddChild(new TextureRect
            {
                Texture = _spriteSystem.Frame0(cat.Icon),
                TextureScale = new Vector2(0.75f, 0.75f),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                VerticalAlignment = VAlignment.Center
            });

            content.AddChild(new Label
            {
                Text = Loc.GetString(cat.Name),
                VerticalAlignment = VAlignment.Center,
                HorizontalExpand = true
            });

            button.AddChild(content);

            var catId = cat.ID;
            button.OnPressed += _ => SelectCategory(catId);
            CategoryList.AddChild(button);
        }

        if (categories.Count > 0)
        {
            SelectCategory(categories[0].ID);
        }
    }

    private void SelectCategory(string categoryId)
    {
        _currentCategory = categoryId;

        foreach (var child in CategoryList.Children)
        {
            if (child is Button btn)
                btn.Pressed = btn.Name == $"CategoryTab_{categoryId}";
        }

        SearchBar.Text = string.Empty;
        RefreshDocumentList();
    }

    private void RefreshDocumentList()
    {
        DocumentList.RemoveAllChildren();

        if (_lastState is null)
            return;

        var query = SearchBar.Text.Trim();

        List<DocumentEntry> filtered;
        if (string.IsNullOrEmpty(query))
        {
            if (_currentCategory is null || !_lastState.DocumentsByCategory.TryGetValue(_currentCategory, out var docs))
                return;

            filtered = docs;
        }
        else
        {
            filtered = _lastState.DocumentsByCategory.Values
                .SelectMany(docs => docs)
                .Where(d => d.Name.Contains(query, StringComparison.OrdinalIgnoreCase))
                .ToList();
        }

        foreach (var doc in filtered)
        {
            DocumentList.AddChild(BuildDocumentRow(doc));
        }

        if (filtered.Count == 0)
        {
            DocumentList.AddChild(new Label
            {
                Text = Loc.GetString("document-printer-no-results"),
                StyleClasses = { "LabelSubText" },
                Margin = new Thickness(4)
            });
        }
    }

    private Control BuildDocumentRow(DocumentEntry doc)
    {
        var row = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 2)
        };

        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(6, 4)
        };

        var labelBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true
        };

        Color? nameColor = doc.Accessible ? null : Color.Gray;

        labelBox.AddChild(new Label
        {
            Text = doc.Name,
            ModulateSelfOverride = nameColor
        });

        if (!string.IsNullOrWhiteSpace(doc.Description))
        {
            labelBox.AddChild(new Label
            {
                Text = doc.Description,
                StyleClasses = { "LabelSubText" },
                ModulateSelfOverride = nameColor
            });
        }

        var printButton = new Button
        {
            Text = Loc.GetString("document-printer-print-button"),
            Disabled = !doc.Accessible
        };

        var docId = doc.Id;
        printButton.OnPressed += _ => OnPrintRequested?.Invoke(docId);

        if (!doc.Accessible)
        {
            var reqNames = doc.RequiredAccess
                .Select(tag => _proto.TryIndex<AccessLevelPrototype>(tag, out var lvl)
                    ? Loc.GetString(lvl.Name ?? tag)
                    : tag);

            row.ToolTip = Loc.GetString("document-printer-locked-tooltip", ("access", string.Join(", ", reqNames)));
            row.TooltipDelay = 0.2f;
        }

        box.AddChild(labelBox);
        box.AddChild(printButton);
        row.AddChild(box);

        return row;
    }
}
